### ISSUE TITLE
Error when generating the dataset

### ISSUE THREAD

**Issue by ejichen** [github-pengge/PyTorch-progressive_growing_of_gans#26]
Hello,
Thanks for the great work! However I'm facing some errors when generating the images dataset. One of them is when I executed the command `python2 h5tool.py create_celeba_hq file_name_to_save /path/to/celeba_dataset/ /path/to/celeba_hq_deltas`, it shows the error message below. How should I solve this? Thank you so much.
```

Traceback (most recent call last):
  File "h5tool.py", line 697, in <module>
    execute_cmdline(sys.argv)
  File "h5tool.py", line 692, in execute_cmdline
    func(**vars(args))
  File "h5tool.py", line 596, in create_celeba_hq
    for idx, img in pool.process_items_concurrently(fields['idx'], process_func=process_func, max_items_in_flight=num_tasks):
  File "h5tool.py", line 161, in process_items_concurrently
    for res in retire_result(): yield res
  File "h5tool.py", line 149, in retire_result
    processed, (prepared, idx) = self.get_result(task_func)
  File "h5tool.py", line 126, in get_result
    raise Exception('%s, %s' % (result.type, result.value))
Exception: <type 'exceptions.ValueError'>, Unable to create correctly shaped tuple from ((420, 1730), (420, 1906), (0, 0))

```

**Comment by cg3575** [comment]
have you solve the problem? I have met the same question.
